dataset_name: "video_demo"
task: "video_demo"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.doc_to_visual_interleave
doc_to_text: !function utils.doc_to_text
doc_to_target: "answer"
process_results: !function utils.process_results
metric_list:
  - metric: mcq_accuracy
    aggregation: !function utils.aggregate_score
    higher_is_better: true
include: _default_template_yaml
